#goal -> is to integrate code, test ,lint , build my forentend  as well as backend
name: CI

on:
    push:
        branches: [master]

jobs:
  frontend-CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Node-Linter
        run: npm run lint

      - name: Run Test Cases
        run: npm test

      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
         username: ${{ vars.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker Image for fe
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/frontend:latest


  backend-CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    needs: frontend-CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: copy example env file to .env
        run: cp .env.example .env
        
      - name: setup go environment
        uses: actions/setup-go@v6
        with:
            go-version: 1.22
            go-version-file: 'go.mod'
            cache-dependency-path: 'go.sum'
      - name: Install dependencies
        run: go mod download
      # Step 4: Verify module integrity
      - name: Verify dependencies
        run: go mod verify
      - name: Go-Linter
        run: go vet
      - name: Run Test Cases
        run: go test ./...
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker Image for be
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/backend:latest
  deploy:
    needs: [frontend-CI, backend-CI]
    uses: ./.github/workflows/cd.yml
    secrets: inherit

